import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "../contexts/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="z-[1] absolute h-6 top-0 left-0 w-full text-center bg-green-900 text-white">
          UTAK-PH Test
        </div>
        <SessionProvider>
          {children}
          </SessionProvider>
      </body>
    </html>
  );
}
